[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"

[deploy]
startCommand = "node dist/mcp/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[env]
MCP_MODE = "http"
NODE_ENV = "production"
LOG_LEVEL = "info"
TRUST_PROXY = "1"
USE_FIXED_HTTP = "true"